# Generated by Django 2.2.12 on 2020-04-21 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 16, 43, 30, 177204, tzinfo=utc)),
        ),
    ]
